var config = {
    "videoBandwidth": 4096,
    "useNicks": false,
    "desktopSharingFirefoxMaxVersionExtRequired": -1,
    "disableAudioLevels": false,
    "audioMixer": false,
    "useIPv6": false,
    "defaultSipNumber": "",
    "audioBandwidth": 128,
    "startBitrate": 800,
    "enableWelcomePage": true,
    "useStunTurn": false,
    "enableRtpStats": true,
    "desktopSharingSources": [
        "screen",
        "window"
    ],
    "bosh": "https://127.0.0.1:7443/http-bind/",
    "enableRecording": false,
    "resolution": 720,
    "hiddenDomain": "recorder.127.0.0.1",
    "enableLipSync": false,
    "minHDHeight": 540,
    "useRoomAsSharedDocumentName": false,
    "recordingType": "colibri",
    "startAudioMuted": 9,
    "desktopSharingFirefoxExtId": "jidesha@meet.jit.si",
    "desktopSharingFirefoxExtensionURL": 
        "https://127.0.0.1:7443/ofmeet/jidesha-0.1.1-fx.xpi",
    "openSctp": true,
    "clientNode": "http://igniterealtime.org/ofmeet/jitsi-meet/",
    "conferences": [],
    "channelLastN": -1,
    "chromeExtensionId": "fohfnhgabmicpkjcpjpjongpijcffaba",
    "desktopSharingFirefoxDisabled": false,
    "adaptiveLastN": false,
    "hosts": {
        "domain": "127.0.0.1",
        "focus": "focus.127.0.0.1",
        "muc": "conference.127.0.0.1",
        "bridge": "jitsi-videobridge.127.0.0.1"
    },
    "logStats": false,
    "useRtcpMux": true,
    "requireDisplayName": false,
    "startVideoMuted": 9,
    "adaptiveSimulcast": false,
    "enforcedBridge": "jitsi-videobridge.127.0.0.1",
    "useBundle": true,
    "disableRtx": true,
    "disableAdaptiveSimulcast": true,
    "minChromeExtVersion": "0.1",
    "disableSimulcast": false,
    "startAudioOnly": false,
    "stereo": false,
    "desktopSharing": "ext",
    "focusUserJid": "focus@127.0.0.1"
};